config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin,controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    registrations: "admins/registrations"
  }

  devise_for :users,controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations"
  }

  namespace :admin do
    root to: "homes#top"
    resources :users, only:[:show, :edit, :update, :destroy] do
     resources :posts, only:[:index, :show, :destroy]
    end
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    get "all_posts" => "homes#all_posts"
    get "favorite_posts" => "homes#favorite_posts"
    get "finder" => "finders#finder", as: "finder"
    get "contact" => "contacts#index"
    post "contact/confirm" => "contacts#confirm"
    post "contact/done" => "contacts#done"
    
    resources :users, only:[:show, :edit, :update, :destroy] do
      get :withdrawal, on: :member
      get :followings, on: :member
      get :followers, on: :member
    end
    resources :posts, only:[:show, :create, :destroy] do
      resource :favorites, only:[:create, :destroy, :show]
      resources :post_comments, only:[:create, :destroy]
   end
   resources :relationships, only:[:create, :destroy]
   

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  mount_uploader :video_id, VideoTopUploader
  
  
  def self.looks(searches, words)
    @post = Post.where("body LIKE ?", "%#{words}%")
  end
  
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  attachment :image
  
  validates :body, presence: true
  validates :image, presence: true, if: -> { video_id.blank? }
  validates :video_id, presence: true, if: -> { image.blank? }
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @user = User.find(params[:user_id])
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_user_posts_path(@post.user)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
 
  <div style="margin-top: 40px;">
   
      <h3><%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"50x50" %><%= @user.user_name %></h3>
        <p><%= @user.introduction %></p>
         
  </div>
  
    <br></br><h4 class="text-center">Posts</h4>
      <div class="row" style="margin-top: 40px;">
        <% @user.posts.each do |post| %>
          <div class="col-md-4 mt-5 d-flex pl-5" style="width: 80%;">
            <div class="d-flex">
              <a href="/admin/users/<%= @user.id %>/posts/<%= post.id %>"><%= attachment_image_tag post, :image, width:"240px", height:"240px" %></a>
            </div>
              <% if post.video_id.present? != false %>
                <div class="d-flex">
                  <a href="/admin/users/<%= @user.id %>/posts/<%= post.id %>"><%= video_tag(post.video_id, width:"240px", height:"240px", :controls => true) %></a>
                </div>
              <% end %>
          </div>
        <% end %>
     </div>
     
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div style="margin-top: 40px;">
    <div style="margin: 0 auto; width: 650px;">
       <div class="mb-2 mt-2 pl-2" style="width: 650px;">
         <%= attachment_image_tag @post.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"30x30" %><%= link_to @post.user.user_name, user_path(@post.user.id) %>
          
             <div class="d-inline-block" style="margin-left: 450px;">
               <%= link_to "投稿を削除", admin_user_post_path, method: :delete, "data-confirm"=>"本当に削除しますか", class:"btn btn-danger" %>
             </div>
         
       </div>
         <div>
           <%= attachment_image_tag @post, :image, :fill, 650, 650 %>
         </div>
           <div style="margin-top: 10px; margin-bottom: 10px;">
             <%= @post.body %>
           </div>
              <% if @post.video_id.present? != false %>
                <div>
                  <%= link_to @post.video_id.url.to_s do %>
                    <%= video_tag(@post.video_id.to_s, width: "100%", height: "100%", :controls => true) %>
                  <% end %>
                </div>
              <% end %>
   
     <div style="margin-top: 30px;">
      <%= link_to "#{@post.favorites.count}件のいいね", post_favorites_path(@post) %>
     </div>
      
            <div style="margin-top: 50px;">
              <h4>COMMENT</h4>
                <% @post.post_comments.each do |post_comment| %>
                  <div>
                    <a href="/users/<%= post_comment.user.id %>"><%= post_comment.user.user_name %></a>
                  </div>
                  
                    <div style="margin-left: 20px; width: 650px;">
                      <%= post_comment.comment %>
                        
                          <div class="d-inline-block" style="margin-left: 450px;">
                            <%= link_to "コメントを削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, class:"btn btn-danger" %>
                          </div>
                        
                    </div>
                <% end %>
            </div>
       
     
    </div>
  </div>
</div>