config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin,controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    registrations: "admins/registrations"
  }

  devise_for :users,controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations"
  }

  namespace :admin do
    root to: "homes#top"
    resources :users, only:[:show, :edit, :update, :destroy] do
     resources :posts, only:[:index, :show, :destroy]
    end
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    get "all_posts" => "homes#all_posts"
    get "favorite_posts" => "homes#favorite_posts"
    get "finder" => "finders#finder", as: "finder"
    get "contact" => "contacts#index"
    post "contact/confirm" => "contacts#confirm"
    post "contact/done" => "contacts#done"
    
    resources :users, only:[:show, :edit, :update, :destroy] do
      get :withdrawal, on: :member
      get :followings, on: :member
      get :followers, on: :member
    end
    resources :posts, only:[:show, :create, :destroy] do
      resource :favorites, only:[:create, :destroy, :show]
      resources :post_comments, only:[:create, :destroy]
   end
   resources :relationships, only:[:create, :destroy]
   

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact include ActiveModel::Model
  
  attr_accessor :name, :email, :content
   
    validates :name, presence: true, length: { maximum: 20 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 30 },
                      format: { with: VALID_EMAIL_REGEX }
    validates :content, presence: true, length: { maximum: 500 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  mount_uploader :video_id, VideoTopUploader
  
  
  def self.looks(searches, words)
    @post = Post.where("body LIKE ?", "%#{words}%")
  end
  
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  attachment :image
  
  validates :body, presence: true
  validates :image, presence: true, if: -> { video_id.blank? }
  validates :video_id, presence: true, if: -> { image.blank? }
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :user
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  attachment :profile_image
         
  
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follower
  
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :user
  
  validates :telephone_number, presence: true
  validates :telephone_number, format: { with: /\A\d{10,11}\z/ }
  validates :full_name, presence: true
  validates :full_name, uniqueness: true
  validates :user_name, presence: true
  validates :email, format: { with: /\A\S+@\S+\.\S+\z/ }
  
  
  def follow(other_user)
    return if self == other_user
    
    relationships.find_or_create_by!(follower: other_user)
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def unfollow(relationship_id)
    relationships.find(relationship_id).destroy!
  end
  
  def self.looks(searches, words)
    @user = User.where("user_name LIKE ?", "%#{words}%")
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    
    before_action :authenticate_admin!
    
    def top
      @users = User.all
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @user = User.find(params[:user_id])
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_user_posts_path(@post.user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
 
 before_action :authenticate_admin!
 
    def show
      @user = User.find(params[:id])
    end
    
   def edit
      @user = User.find(params[:id])
   end
   
   def update
      @user = User.find(params[:id])
      @user.update!(user_params)
      redirect_to admin_user_path
   end
    
   def destroy
     @user = User.find(params[:id])
     @user.destroy
     redirect_to "/admin"
   end
    
    private
      def user_params
        params.require(:user).permit(:full_name, :email, :telephone_number)
      end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?


 protected
  
  def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :user_name, :telephone_number, :is_active])
       devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :user_name, :telephone_number, :profile_image_id, :is_active])
  end
end 

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatPride</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/2aae60316c.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
         <a class="navbar-brand p-3" href="/"><%= image_tag("logo.png") %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
           <div class="collapse navbar-collapse" id="navbarNavDropdown">
             <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <a class="fas fa-user nav-link text-dark" href="/admin">&nbsp;&nbsp;Users</a>
                </li>
                <li class="nav-item">
                  <a class="fas fa-sign-out-alt nav-link text-dark" rel="nofollow" data-method="delete" href="/admin/sign_out">&nbsp;Log out</a>
                  </li>
    
              <% elsif user_signed_in? %>
                <li class="nav-item">
                  <a class="fas fa-home nav-link text-dark" href="/">&nbsp;Home</a>
                </li>
                <li class="nav-item">
                  <a class="fas fa-user nav-link text-dark" href="/users/<%= current_user.id %>">&nbsp;&nbsp;Profile</a>
                </li>
                <li class="nav-item">
                  <a class="fas fa-search nav-link text-dark" href="/finder">&nbsp;Search</a>
                </li>
                <li class="nav-item">
                  <a class="fas fa-sign-out-alt nav-link text-dark" rel="nofollow" data-method="delete" href="/users/sign_out">&nbsp;Log out</a>
                </li>
              <% else %>
                <li class="nav-item">
                  <a class="fas fa-cat nav-link text-dark" href="/about">&nbsp;About</a>
                </li>
                <li class="nav-item">
                  <a class="fas fa-user-plus nav-link text-dark" href="/users/sign_up">&nbsp;Sign up</a>
                </li>
                <li class="nav-item">
                  <a class="fas fa-sign-in-alt nav-link text-dark" href="/users/sign_in">&nbsp;&nbsp;Log in</a>
                </li>
              <% end %> 
             </ul>
           </div>
          </div>
        </nav>
    </header>
    <%= yield %>
     <footer class="border-top" style="margin-top: 20px;"></footer>
  </body>
</html>